services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: envportal-guacd
    restart: unless-stopped
    volumes:
      - ./guacamole-drive:/drive

  guacamole-db:
    image: postgres:15-alpine
    container_name: envportal-guacamole-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_pass
    volumes:
      - envportal-guacamole-db:/var/lib/postgresql/data
      - ./guacamole-init:/docker-entrypoint-initdb.d:ro

  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: envportal-guacamole
    restart: unless-stopped
    depends_on:
      - guacd
      - guacamole-db
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: guacamole-db
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: guacamole_pass
      QUICKCONNECT_ENABLED: "true"
    volumes:
      - ./guacamole-drive:/drive
    ports:
      - "0.0.0.0:8088:8080"

  guacamole-https:
    image: nginx:1.27-alpine
    container_name: envportal-guacamole-https
    restart: unless-stopped
    depends_on:
      - guacamole
    ports:
      - "0.0.0.0:8443:443"
    volumes:
      - ./guacamole-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro

volumes:
  envportal-guacamole-db:
